### ISSUE TITLE
Property instead of attribute

### ISSUE THREAD

**Issue by TrySound** [jwilsson/domtokenlist#2]
[here](https://github.com/jwilsson/domtokenlist/blob/master/dist/domtokenlist.js#L41) you must use property name instead of getAttribute based on the specification: [stackoverflow: IDL Attribute](http://stackoverflow.com/questions/12354918/what-does-idl-attribute-mean-in-the-whatwg-html5-standard-document)

**Comment by TrySound** [comment]
Add tag, please.

**Comment by jwilsson** [comment]
Right, `1.0.2` is now tagged.

**Comment by TrySound** [comment]
@jwilsson Cool! Thanks!
